### PR TITLE
Home page

### PR DESCRIPTION
**Pull request by brandynm34**
Because I used a floating image is there a way to move the dog image more left or is that just how the format is?

### CODE REVIEW

**Comment by rockygg** [comment]
Can you please provide a screenshot of what you're experiencing? google chrome has a really good screenshot extension called "Full page screen capture"

**Comment by brandynm34** [comment]
screen shot 2017-09-14 at 1 48 34 pm

Like for the dog image because i specified float right in the   "style="float:right;"...</img> is there a way i can move the image more left?

**Comment by rockygg** [comment]
I think you'd have better luck with something more like 
```
<div class="row">
    <div class="col-md-8">
        <p>text about dog</p>
    </div>
    <div class="col-md-4">
        <img src="[image file path]" class="img-responsive">
    </div>
</div>
```
and you can adjust the column sizes to move the image more left or right
ex: to move the dog image more to the middle of the page, try changing both columns to `col-md-6`
just remember to have both columns add up to 12

**Comment by rockygg** [comment]
Also when you're done making your changes, you don't have to close this PR and open a new one. Just push them up to this same branch and your edits will appear in this PR. Just slack me or tag me when you're done

**Review by rockygg — CHANGES_REQUESTED** [review]
This looks great so far, but I think you forgot to add a footer

**Pull request merged**
